services:
  gib_portfolio:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: with-docker-multi-env-development
    container_name: gib_portfolio
    networks:
      - node_apps
    ports:
      - "3000:3000"
    tty: true
    restart: unless-stopped
networks:
  node_apps:
    external: true

